server:
  port: 8084

spring:
  application:
    name: payment-service

  datasource:
    url:
    username: sa
    password: 123
    driver-class-name:
    hikari:
      pool-name: ApplicationHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
    open-in-view: false

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 2000
            read-timeout: 3000

